apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniuser
spec:
  selector:
    matchLabels:
      app: miniuser
  replicas: 1
  template:
    metadata:
      labels:
        app: miniuser

    spec:
      containers:
      - name: miniuser
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
        resources:
          requests:
            memory: 300Mi
            cpu: 50m


---


apiVersion: v1
kind: Service

metadata:
  name: miniuser

spec:
  selector:
    app: miniuser

  ports:
    - name: http
      port: 8888
    



  type: ClusterIP
